package com.kormax.felicatool.util

import androidx.annotation.DrawableRes
import com.kormax.felicatool.R

/** Maps shared service icon names to Android drawable resources. */
object ServiceIconMapper {
    private val iconMap =
        mapOf(
            "service_icsca" to R.drawable.service_icsca,
            "service_paspy" to R.drawable.service_paspy,
            "service_kinoca" to R.drawable.service_kinoca,
            "service_hareca" to R.drawable.service_hareca,
            "service_ayuca" to R.drawable.service_ayuca,
            "service_cjrc" to R.drawable.service_cjrc,
            "service_emica" to R.drawable.service_emica,
            "service_felica_kazasu_folder" to R.drawable.service_felica_kazasu_folder,
            "service_felica_lite" to R.drawable.service_felica_lite,
            "service_osaifu_keitai" to R.drawable.service_osaifu_keitai,
            "service_felica_networks" to R.drawable.service_felica_networks,
            "service_felica_pocket" to R.drawable.service_felica_pocket,
            "service_felica_secure_id" to R.drawable.service_felica_secure_id,
            "service_aime" to R.drawable.service_aime,
            "service_bandai_namco_passport" to R.drawable.service_bandai_namco_passport,
            "service_enekey" to R.drawable.service_enekey,
            "service_konami_e_amusement" to R.drawable.service_konami_e_amusement,
            "service_mobiry_days" to R.drawable.service_mobiry_days,
            "service_nesica" to R.drawable.service_nesica,
            "service_hayakaken" to R.drawable.service_hayakaken,
            "service_icoca" to R.drawable.service_icoca,
            "service_iruca" to R.drawable.service_iruca,
            "service_kitaca" to R.drawable.service_kitaca,
            "service_kumamon" to R.drawable.service_kumamon,
            "service_manaca" to R.drawable.service_manaca,
            "service_nanaco" to R.drawable.service_nanaco,
            "service_ndef" to R.drawable.service_ndef,
            "service_nimoca" to R.drawable.service_nimoca,
            "service_octopus" to R.drawable.service_octopus,
            "service_okica" to R.drawable.service_okica,
            "service_pasmo" to R.drawable.service_pasmo,
            "service_edy" to R.drawable.service_edy,
            "service_rakuten_edy" to R.drawable.service_rakuten_edy,
            "service_rakuten_point" to R.drawable.service_rakuten_point,
            "service_sapica" to R.drawable.service_sapica,
            "service_shenzen_tong" to R.drawable.service_shenzen_tong,
            "service_sugoca" to R.drawable.service_sugoca,
            "service_suica" to R.drawable.service_suica,
            "service_suica_plus" to R.drawable.service_suica_plus,
            "service_toica" to R.drawable.service_toica,
            "service_waon" to R.drawable.service_waon,
            "service_asaca" to R.drawable.service_asaca,
            "service_docard" to R.drawable.service_docard,
            "service_asahikawa" to R.drawable.service_asahikawa,
            "service_aizu_noruca" to R.drawable.service_aizu_noruca,
            "service_noruca" to R.drawable.service_noruca,
            "service_fukushima" to R.drawable.service_fukushima,
            "service_ibappi" to R.drawable.service_ibappi,
            "service_nicepass" to R.drawable.service_nicepass,
            "service_ryuto" to R.drawable.service_ryuto,
            "service_shikoku" to R.drawable.service_shikoku,
            "service_desuca" to R.drawable.service_desuca,
            "service_iyotetsu" to R.drawable.service_iyotetsu,
            "service_hanica" to R.drawable.service_hanica,
            "service_kagoshima" to R.drawable.service_kagoshima,
            "service_iwasaki" to R.drawable.service_iwasaki,
            "service_rapica" to R.drawable.service_rapica,
            "service_randen" to R.drawable.service_randen,
            "service_kitami_bus" to R.drawable.service_kitami_bus,
            "service_itappy" to R.drawable.service_itappy,
            "service_nicopa" to R.drawable.service_nicopa,
            "service_kururu" to R.drawable.service_kururu,
            "service_odeca" to R.drawable.service_odeca,
            "service_ica" to R.drawable.service_ica,
            "service_cica" to R.drawable.service_cica,
            "service_tsukica" to R.drawable.service_tsukica,
            "service_toyama" to R.drawable.service_toyama,
            "service_ecomyca" to R.drawable.service_ecomyca,
            "service_passca" to R.drawable.service_passca,
            "service_nagasaki_smart" to R.drawable.service_nagasaki_smart,
            "service_ntasu" to R.drawable.service_ntasu,
            "service_kmt_commet" to R.drawable.service_kmt_commet,
            "service_kmt_jelajah" to R.drawable.service_kmt_jelajah,
            "service_dmtcl" to R.drawable.service_dmtcl,
            "service_setamaru" to R.drawable.service_setamaru,
            "service_saitama_railway" to R.drawable.service_saitama_railway,
            "service_nankai" to R.drawable.service_nankai,
            "service_jal" to R.drawable.service_jal,
            "service_ana" to R.drawable.service_ana,
            "service_yodobashi_goldpoint" to R.drawable.service_yodobashi_goldpoint,
            "service_unknown" to R.drawable.service_unknown,
            "service_kesaka" to R.drawable.service_kesaka,
            "service_quicpay" to R.drawable.service_quicpay,
            "service_karuwaza_club" to R.drawable.service_karuwaza_club,
            "service_ezlink" to R.drawable.service_ezlink,
            "service_skyrail" to R.drawable.service_skyrail,
            "service_yamanashi_kotsu" to R.drawable.service_yamanashi_kotsu,
            "service_miwa" to R.drawable.service_miwa,
            "service_miwa_fkl" to R.drawable.service_miwa_fkl,
            "service_miwa_iel" to R.drawable.service_miwa_iel,
            "service_miwa_keymo" to R.drawable.service_miwa_keymo,
            "service_speedpass" to R.drawable.service_speedpass,
            "service_ampm" to R.drawable.service_ampm,
            "service_san_in_shinpan" to R.drawable.service_san_in_shinpan,
            "service_honda_c_card" to R.drawable.service_honda_c_card,
            "service_starbucks_touch" to R.drawable.service_starbucks_touch,
            "service_clavis" to R.drawable.service_clavis,
            "service_hcmc" to R.drawable.service_hcmc,
            "service_luluca" to R.drawable.service_luluca,
        )

    @DrawableRes
    fun iconFor(providerName: String): Int? {
        val iconName = ServiceIconCatalog.iconNameFor(providerName) ?: return null
        return iconMap[iconName]
    }
}
