package com.kormax.felicatool.felica

/** Enum representing the Service Attribute with its properties. */
enum class ServiceAttribute(
    val value: Int,
    val type: ServiceType,
    val mode: ServiceMode,
    val authenticationRequired: Boolean,
    val pinRequired: Boolean,
) {
    RANDOM_RW_WITH_KEY(0b001000, ServiceType.RANDOM, ServiceMode.READ_WRITE, true, false),
    RANDOM_RW_WITHOUT_KEY(0b001001, ServiceType.RANDOM, ServiceMode.READ_WRITE, false, false),
    RANDOM_RO_WITH_KEY(0b001010, ServiceType.RANDOM, ServiceMode.READ_ONLY, true, false),
    RANDOM_RO_WITHOUT_KEY(0b001011, ServiceType.RANDOM, ServiceMode.READ_ONLY, false, false),
    CYCLIC_RW_WITH_KEY(0b001100, ServiceType.CYCLIC, ServiceMode.READ_WRITE, true, false),
    CYCLIC_RW_WITHOUT_KEY(0b001101, ServiceType.CYCLIC, ServiceMode.READ_WRITE, false, false),
    CYCLIC_RO_WITH_KEY(0b001110, ServiceType.CYCLIC, ServiceMode.READ_ONLY, true, false),
    CYCLIC_RO_WITHOUT_KEY(0b001111, ServiceType.CYCLIC, ServiceMode.READ_ONLY, false, false),
    PURSE_RW_WITH_KEY(0b010000, ServiceType.PURSE, ServiceMode.READ_WRITE, true, false),
    PURSE_RW_WITHOUT_KEY(0b010001, ServiceType.PURSE, ServiceMode.READ_WRITE, false, false),
    PURSE_RO_WITH_KEY(0b010110, ServiceType.PURSE, ServiceMode.READ_ONLY, true, false),
    PURSE_RO_WITHOUT_KEY(0b010111, ServiceType.PURSE, ServiceMode.READ_ONLY, false, false),
    PURSE_DECREMENT_WITH_KEY(0b010100, ServiceType.PURSE, ServiceMode.DECREMENT, true, false),
    PURSE_DECREMENT_WITHOUT_KEY(0b010101, ServiceType.PURSE, ServiceMode.DECREMENT, false, false),
    PURSE_CASHBACK_WITH_KEY(0b010010, ServiceType.PURSE, ServiceMode.CASHBACK, true, false),
    PURSE_CASHBACK_WITHOUT_KEY(0b010011, ServiceType.PURSE, ServiceMode.CASHBACK, false, false),
    RANDOM_RW_WITHOUT_KEY_WITH_PIN(
        0b101001,
        ServiceType.RANDOM,
        ServiceMode.READ_WRITE,
        false,
        true,
    ),
    RANDOM_RW_WITH_KEY_WITH_PIN(0b101000, ServiceType.RANDOM, ServiceMode.READ_WRITE, true, true),
    RANDOM_RO_WITHOUT_KEY_WITH_PIN(
        0b101011,
        ServiceType.RANDOM,
        ServiceMode.READ_ONLY,
        false,
        true,
    ),
    RANDOM_RO_WITH_KEY_WITH_PIN(0b101010, ServiceType.RANDOM, ServiceMode.READ_ONLY, true, true),
    CYCLIC_RW_WITHOUT_KEY_WITH_PIN(
        0b101101,
        ServiceType.CYCLIC,
        ServiceMode.READ_WRITE,
        false,
        true,
    ),
    CYCLIC_RW_WITH_KEY_WITH_PIN(0b101100, ServiceType.CYCLIC, ServiceMode.READ_WRITE, true, true),
    CYCLIC_RO_WITHOUT_KEY_WITH_PIN(
        0b101111,
        ServiceType.CYCLIC,
        ServiceMode.READ_ONLY,
        false,
        true,
    ),
    CYCLIC_RO_WITH_KEY_WITH_PIN(0b101110, ServiceType.CYCLIC, ServiceMode.READ_ONLY, true, true),
    PURSE_CASHBACK_WITHOUT_KEY_WITH_PIN(
        0b110011,
        ServiceType.PURSE,
        ServiceMode.CASHBACK,
        false,
        true,
    ),
    PURSE_CASHBACK_WITH_KEY_WITH_PIN(0b110010, ServiceType.PURSE, ServiceMode.CASHBACK, true, true),
    PURSE_DECREMENT_WITHOUT_KEY_WITH_PIN(
        0b110101,
        ServiceType.PURSE,
        ServiceMode.DECREMENT,
        false,
        true,
    ),
    PURSE_DECREMENT_WITH_KEY_WITH_PIN(
        0b110100,
        ServiceType.PURSE,
        ServiceMode.DECREMENT,
        true,
        true,
    ),
    PURSE_RW_WITHOUT_KEY_WITH_PIN(0b110001, ServiceType.PURSE, ServiceMode.READ_WRITE, false, true),
    PURSE_RW_WITH_KEY_WITH_PIN(0b110000, ServiceType.PURSE, ServiceMode.READ_WRITE, true, true),
    PURSE_RO_WITHOUT_KEY_WITH_PIN(0b110111, ServiceType.PURSE, ServiceMode.READ_ONLY, false, true),
    PURSE_RO_WITH_KEY_WITH_PIN(0b110110, ServiceType.PURSE, ServiceMode.READ_ONLY, true, true),
}
