package com.kormax.felicatool.util

/** Shared service-provider to icon-name catalog. Platform UIs map these names to local assets. */
object ServiceIconCatalog {
    private val iconNames =
        mapOf(
            "ICSCA" to "service_icsca",
            "PASPY" to "service_paspy",
            "KINOCA" to "service_kinoca",
            "HARECA" to "service_hareca",
            "AYUCA" to "service_ayuca",
            "CJRC" to "service_cjrc",
            "EMICA" to "service_emica",
            "FELICA_KAZASU_FOLDER" to "service_felica_kazasu_folder",
            "FELICA_LITE" to "service_felica_lite",
            "OSAIFU_KEITAI" to "service_osaifu_keitai",
            "FELICA_NETWORKS" to "service_felica_networks",
            "FELICA_POCKET" to "service_felica_pocket",
            "HAYAKAKEN" to "service_hayakaken",
            "ICOCA" to "service_icoca",
            "IRUCA" to "service_iruca",
            "KITACA" to "service_kitaca",
            "KUMAMON" to "service_kumamon",
            "MANACA" to "service_manaca",
            "NANACO" to "service_nanaco",
            "NDEF" to "service_ndef",
            "NIMOCA" to "service_nimoca",
            "OCTOPUS" to "service_octopus",
            "OKICA" to "service_okica",
            "PASMO" to "service_pasmo",
            "EDY" to "service_edy",
            "EDY_RAKUTEN" to "service_rakuten_edy",
            "RAKUTEN_POINT" to "service_rakuten_point",
            "SAPICA" to "service_sapica",
            "SHENZEN_TONG" to "service_shenzen_tong",
            "SUGOCA" to "service_sugoca",
            "SUICA" to "service_suica",
            "SUICA_PLUS" to "service_suica_plus",
            "TOICA" to "service_toica",
            "WAON" to "service_waon",
            "ASACA_DOCARD" to "service_asaca_docard",
            "NORUCA" to "service_noruca",
            "IBAPPI" to "service_ibappi",
            "NICEPASS" to "service_nicepass",
            "RYUTO" to "service_ryuto",
            "SHIKOKU" to "service_shikoku",
            "DESUCA" to "service_desuca",
            "IYOTETSU" to "service_iyotetsu",
            "HANICA" to "service_hanica",
            "KAGOSHIMA" to "service_kagoshima",
            "IWASAKI" to "service_iwasaki",
            "RAPICA" to "service_rapica",
            "RANDEN" to "service_randen",
            "KITAMI_BUS" to "service_kitami_bus",
            "ITAPPY" to "service_itappy",
            "NICOPA" to "service_nicopa",
            "KURURU" to "service_kururu",
            "ODECA" to "service_odeca",
            "ICA" to "service_ica",
            "CICA" to "service_cica",
            "TSUKICA" to "service_tsukica",
            "TOYAMA" to "service_toyama",
            "ECOMYCA" to "service_ecomyca",
            "PASSCA" to "service_passca",
            "NAGASAKI_SMART" to "service_nagasaki_smart",
            "KMT_COMMET" to "service_kmt_commet",
            "KMT_JELAJAH" to "service_kmt_jelajah",
            "SETAMARU" to "service_setamaru",
            "SAITAMA_RAILWAY" to "service_saitama_railway",
            "NANKAI" to "service_nankai",
            "JAL" to "service_jal",
            "ANA" to "service_ana",
            "YODOBASHI_GOLDPOINT" to "service_yodobashi_goldpoint",
            "UNFUSED" to "service_unknown",
            "KESAKA" to "service_kesaka",
            "QUICPAY" to "service_quicpay",
            "KARUWAZA_CLUB" to "service_karuwaza_club",
            "EZLINK" to "service_ezlink",
            "SKYRAIL" to "service_skyrail",
            "YAMANASHI_KOTSU" to "service_yamanashi_kotsu",
            "MIWA" to "service_miwa",
            "MIWA_FKL" to "service_miwa_fkl",
            "MIWA_IEL" to "service_miwa_iel",
            "MIWA_KEYMO" to "service_miwa_keymo",
            "SPEEDPASS" to "service_speedpass",
            "AMPM" to "service_ampm",
            "SAN_IN_SHINPAN" to "service_san_in_shinpan",
            "HONDA_C_CARD" to "service_honda_c_card",
            "STARBUCKS_TOUCH" to "service_starbucks_touch",
            "CLAVIS" to "service_clavis",
            "HCMC" to "service_hcmc",
            "LULUCA" to "service_luluca",
        )

    fun iconNameFor(providerName: String): String? {
        return iconNames[providerName.trim().uppercase()]
    }

    fun isKnownIconName(iconName: String): Boolean {
        return iconName in iconNames.values
    }
}
